# Generated by Django 5.0.4 on 2024-05-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
